### ISSUE TITLE
Skipped test fails because of preq content-encoding header stripping

### ISSUE THREAD

**Issue by mdholloway** [wikimedia/service-template-node#101] opened 2018-03-21 17:17 UTC
In 81255a0e a test for static file content encoding was skipped when it began to fail because the response no longer contained an 'content-encoding' response header with a value containing 'gzip'.  This appears to have been broken by a change in preq to strip the header we're testing for: https://github.com/wikimedia/preq/commit/55e2d285c310dae302907e283def913d55292b0e

I tested and confirmed that removing the header-stripping behavior from preq fixes the test.

**Comment by d00rman** [comment] 2018-06-22 17:55
Actually, this is a feature, not a bug :) `preq` behaves correctly because it doesn't return the gzipped content, but rather its uncompressed version, so the `content-encoding` header should be removed. I modified the test slightly in #107 to reflect that.

**Comment by d00rman** [comment] 2018-06-22 17:57
Closing as from my POV the issue is resolved in that the test is being performed now. Please reopen if this is still an issue for you.

**Comment by mdholloway** [comment] 2018-06-22 17:58
LGTM!

**Closed by d00rman** 2018-06-22 17:57 UTC
